---
- name: "configuration ansible playbook backend."
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    # Get the environment variables from CircleCI and add to the EC2 instance
  environment:
    - DOCKERHUB_USERNAME: "{{ lookup('env', 'DOCKERHUB_USERNAME')}}"
    - DOCKERHUB_PASS: "{{ lookup('env', 'DOCKERHUB_PASS')}}"

  roles:
    - deploy